# Generated by Django 5.2.1 on 2025-06-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи', max_length=50, verbose_name='Article title')),
                ('short_content', models.CharField(help_text='Краткое содержание статьи', max_length=150, verbose_name='Brief article content')),
                ('content', models.TextField(help_text='Статья', verbose_name='Content')),
                ('image', models.ImageField(blank=True, help_text='Прилагаемая картинка', null=True, upload_to='articles/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(to='insurance_agency.userprofile')),
            ],
        ),
    ]
