# Generated by Django 5.2.1 on 2025-06-01 22:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок отзыва', max_length=60, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Review title')),
                ('content', models.TextField(blank=True, help_text='Содержание отзыва', null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Review content')),
                ('rate', models.CharField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Нормально'), ('2', 'Плохо'), ('1', 'Ужасно')], help_text='Оценка', max_length=10, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_agency.userprofile')),
            ],
        ),
    ]
