# Generated by Django 5.2.1 on 2025-06-01 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_string', models.CharField(max_length=10, unique=True, verbose_name='Promo code')),
                ('discount_type', models.CharField(choices=[('%', 'Percent'), ('$', 'Amount')], default='$', help_text='Тип скидки (процент/фиксированная)', max_length=8)),
                ('amount', models.IntegerField(help_text='Величина скидки (%/сумма)', validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_one', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_period', models.IntegerField(default=12, help_text='Срок действия (в месяцах)', verbose_name='Validity period')),
            ],
        ),
    ]
